services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # 👈 WEB UI AT http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    user: "0:0"
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080" # 👈 KAFKA WEB UI AT http://localhost:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: api-gateway
    command: node dist/apps/api-gateway/main.js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - rabbitmq
      - kafka

  tasks:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tasks
    command: node dist/apps/tasks/main.js
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - rabbitmq
      - kafka

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: auth-service
    command: node dist/apps/auth-service/main.js
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

volumes:
  rabbitmq_data:
  kafka_data: